### ISSUE TITLE
xs.t fails on ActiveState Perl 5.24.1 64bit

### ISSUE THREAD

**Issue by plicease** [genio/Alien-libuv#3]
```
N:\home\ollisg\dev\Alien-libuv>prove -bvm t/xs.t
t/xs.t ..
# Seeded srand with seed '20170814' from local date.
ok 1 - Alien::libuv responds to: cflags libs dynamic_libs bin_dir
Use of uninitialized value $verbose in numeric gt (>) at N:/home/ollisg/perl5/activestate/x64/v5.24.1/lib/perl5/Test/Alien.pm line 274.
not ok 2 - xs
# Failed test 'xs'
# at t/xs.t line 10.
#   ExtUtils::CBuilder->compile failed
#     error building dll file from 'testalienJaIXh/test.c' at N:/lang/perl/activestate/x64/v5.24.1/lib/ExtUtils/CBuilder/Platform/Windows.pm line 129.
#     N:\lang\perl\ACTIVE~1\x64\V524~1.1\site\bin\gcc.exe -c -s -O2 -DWIN32 -DWIN64 -DCONSERVATIVE -DPERL_TEXTMODE_SCRIPTS -DUSE_SITECUSTOMIZE -DPERL_IMPLICIT_CONTEXT -DPERL_IMPLICIT_SYS -fwrapv -fno-
strict-aliasing -mms-bitfields -IN:/home/ollisg/dev/Alien-libuv/blib/lib/auto/share/dist/Alien-libuv/include -s -O2 -I"N:\lang\perl\activestate\x64\v5.24.1\lib\CORE" -I"C:\MinGW\x86_64-w64-mingw32\inc
lude" -o "testalienJaIXh\test.o" "testalienJaIXh\test.c"
#     In file included from N:/home/ollisg/dev/Alien-libuv/blib/lib/auto/share/dist/Alien-libuv/include/uv.h:60:0,
#                      from testalienJaIXh/test.xs:5:
#     N:/home/ollisg/dev/Alien-libuv/blib/lib/auto/share/dist/Alien-libuv/include/uv-win.h:257:5: error: unknown type name 'SRWLOCK'
ok 3 - xs subtest {
    1..0 # SKIP subtest requires xs success
}
1..3
Dubious, test returned 1 (wstat 256, 0x100)
Failed 1/3 subtests

Test Summary Report
-------------------
t/xs.t (Wstat: 256 Tests: 3 Failed: 1)
  Failed test:  2
  Non-zero exit status: 1
Files=1, Tests=3,  1 wallclock secs ( 0.02 usr +  0.02 sys =  0.03 CPU)
Result: FAIL
```

This was using the Makefile.mingw method in my mingw-make branch.  The regular autoconf route failed on this platform because for some reason libuv did not install the .pc file.

The 32bit build failed on Alien-Build something with Test::Alien.  Although I think that is a bug in ActivePerl not in AB.

The mingw-make branch works on Strawberry Perl, and neither branch works on ActiveState, so this bug shouldn't block merging the mingw-make branch.

**Comment by plicease** [comment]
<strike>That is to say it works on Strawberry 32bit.  It would be good to also try Strawberry 64bit to see this is a 32/64 bit issue.</strike>

Same test passes on Strawberry 64.  Definitely an ActiveState issue.  The compiler for AS is older than on Strawberry Perl.  Since I have been having other problems with the gcc that comes with AS I think that might be the problem.

**Comment by genio** [comment]
AppVeyor testing seems to be going well with Strawberry Perl now: https://ci.appveyor.com/project/genio/alien-libuv

ActiveState support seems to be something we cannot count on moving forward.

**Comment by plicease** [comment]
I feel a little terrible that I opened this in the first place :/

**Comment by genio** [comment]
No worries. Figuring out the proper flags for the ```SRWLOCK``` error shown allowed us to get over the hump of properly testing on Windows with Strawberry.

I'm going to close this one out for now as I think we're as good as we can be for the time being.
